fixed validation

diff --git a/snap/hooks/configure b/snap/hooks/configure
--- a/snap/hooks/configure
+++ b/snap/hooks/configure
@@ -1,11 +1,8 @@
 #!/bin/sh
 
-DEFAULT_FEATURE_GATES=""
-
 get_feature_gates() {
   value="$(snapctl get feature-gates)"
-  if [ -z "$value" ]; then
-    value="$DEFAULT_FEATURE_GATES"
+  if [ -n "$value" ]; then
     set_feature_gates "$value"
   fi
   echo "$value"
@@ -17,13 +14,16 @@ set_feature_gates() {
 
 handle_feature_gates() {
     feature_gates="$(get_feature_gates)"
-
-    # Validate
-    if ! "$SNAP"/bin/otelcol validate  --feature-gates="$feature_gates" > /dev/null 2>&1; then
-        echo "\"$feature_gates\" is not a valid feature gate definition" >&2
-        return 1
-    fi    
-    
+    if [ -n "$feature_gates" ]; then
+        # Validate
+        otelcol validate --feature-gates="$feature_gates" 2>&1 | grep --ignore-case --quiet "no such feature gate" 
+        return_code=$?
+        # return code 0 means grep found a matching string
+        if [ $return_code -eq 0 ] ; then
+            echo "\"$feature_gates\" is not a valid feature gate definition" >&2
+            return 1
+        fi    
+    fi
     set_feature_gates "$feature_gates"
     snapctl restart opentelemetry-collector.opentelemetry-collector
 }
